function [] = transform_select_diffeomorphism_call(scr,eventdata)
    fh = dialog('units','pixels',...
        'position',[300 300 600 130],...
        'menubar','none',...
        'name','Select Real World/C-Space to Sphere World diffeomorphism',...
        'numbertitle','off',...
        'resize','off');
    pp = uicontrol('style','pop',...
        'units','pixels',...
        'position',[20 80 520 30],...
        'string',{'Analytic (Koditschek-Rimon)',...
        'Polynomial (Lionis-Papageorgiou-Kyriakopoulos)'});
    ed = uicontrol('style','edit',...
        'units','pix',...
        'position',[20 30 520 30],...
        'fontsize',16,'string','select');

    set(pp, 'callback', @pp_call);  % Set the callback.

    function [] = pp_call(varargin)
        P = get(pp, {'string','val'});  % Get the user's choice.
        set(ed, 'string', P{1}{P{2}});  % Assign the user's choice to the edit.
    end
end