function [fig] = init_figure
ScrSz = get(0,'Screensize'); % initially on selected screen->maximized there

if ScrSz(4) > 2*ScrSz(3)
    ScrSz(3) = ScrSz(3) /2;
end

fig = figure(...
   'Name'       , 'Navigation Function Simulation Toolbox',...
   'NumberTitle', 'off',...
   'Units'      , 'pixels',...
   'Position'   , [ScrSz(1)+10, ScrSz(2)+70, ScrSz(3)-150, ScrSz(4)-150],...
   'MenuBar'    , 'none',...
   'Toolbar'    , 'figure',...
   'CloseRequestFcn', @close_nfsimgui);
