function [panels] = init_panel(fig)
h_panel = uipanel(...
    'Parent'    , fig,...
    'Title'     , {'Simulation', 'Parameters'},...
    'FontSize'  , 12,...
    'BackgroundColor','white',...
    'Units'     , 'normalized',...
    'Position'  , [0.01, 0.1, 0.1, 0.8]);

h_button_navigate = uicontrol(...
    'Parent'    , h_panel,...
    'Units'     , 'normalized',...
    'Position'  , [0.1, 0.8, 0.8, 0.08],...
    'string'    , 'Navigate',...
    'Enable'    , 'off',...
    'userdata'  , 0,...
    'callback'  , @navigate_call);

h_button_pause = uicontrol(...
    'Parent'    , h_panel,...
    'Units'     , 'normalized',...
    'Position'  , [0.1, 0.7, 0.8, 0.08],...
    'string'    , 'Pause',...
    'Enable'    , 'off',...
    'userdata'  , 0,...
    'callback'  , @pause_call);

h_button_stop = uicontrol(...
    'Parent'    , h_panel,...
    'Units'     , 'normalized',...
    'Position'  , [0.1, 0.6, 0.8, 0.08],...
    'string'    , 'Stop',...
    'Enable'    , 'off',...
    'userdata'  , 0,...
    'callback'  , @stop_call);

h_slider_k = sliderPanel(...
    'Parent'    , h_panel, ...
    'Title'     , 'Parameter k', ...
    'Position'  , [0.1, 0.4, 0.8, 0.15], ...
    'Backgroundcolor', [0.9,0.9,0.9],...
    'Min'       , 2, ...
    'Max'       , 10, ...
    'Value'     , 3, ...
    'Sliderstep', [1/80, 1/16], ...
    'FontName'  , 'Verdana', ...
    'Callback'  , @slider_k_callback);

h_field_plot_resolution = sliderPanel(...
    'Parent'    , h_panel, ...
    'Title'     , 'Field Resolution', ...
    'Position'  , [0.1, 0.1, 0.8, 0.15], ...
    'Backgroundcolor', [0.9,0.9,0.9],...
    'Min'       , 10, ...
    'Max'       , 1000, ...
    'Value'     , 50, ...
    'Sliderstep', [0.01, 0.1], ...
    'FontName'  , 'Verdana', ...
    'Callback'  , @field_plot_resolution);

h_auto_k = uicontrol(...
    'Parent'    , h_panel,...
    'style'     , 'checkbox',...
    'units'     , 'normalized',...
    'position'  , [0.1, 0.3, 0.8, 0.08],...
    'string'    , 'Auto k',...
    'Callback'  , @auto_k_call);

set(h_slider_k, 'Enable', 'off')
set(h_auto_k, 'Enable', 'off')
set(h_field_plot_resolution, 'Enable', 'off')

%% data out
panels.h_panel = h_panel;
panels.h_button_navigate = h_button_navigate;
panels.h_button_pause = h_button_pause;
panels.h_button_stop = h_button_stop;
panels.h_slider_k = h_slider_k;
panels.h_field_plot_resolution = h_field_plot_resolution;
panels.h_auto_k = h_auto_k;
