function [menus] = init_menus(fig)
menus = menubar(fig);

[h_uimenu_File_item_open, h_uimenu_File_item_save] =...
    file_menu(menus.h_uimenu_File);

edit_menu(menus.h_uimenu_Edit);

[h_uimenu_World_item, h_uimenu_World_place_obstacle] = ...
    world_menu(menus.h_uimenu_World);

h_uimenu_Transform_item = diffeomorphism_menu(menus.h_uimenu_Transform);

h_uimenu_Navigation_item = navigation_menu(menus.h_uimenu_Navigation);

h_uimenu_Help_item = help_menu(menus.h_uimenu_Help);

% data out
menus.h_uimenu_File_item_open = h_uimenu_File_item_open;
menus.h_uimenu_File_item_save = h_uimenu_File_item_save;
menus.h_uimenu_World_item = h_uimenu_World_item;
menus.h_uimenu_World_place_obstacle = h_uimenu_World_place_obstacle;
menus.h_uimenu_Transform_item = h_uimenu_Transform_item;
menus.h_uimenu_Navigation_item = h_uimenu_Navigation_item;
menus.h_uimenu_Help_item = h_uimenu_Help_item;

function [menus] = menubar(fig)
h_uimenu_File = uimenu(fig, 'label', 'File');
h_uimenu_Edit = uimenu(fig, 'label', 'Edit');
h_uimenu_World = uimenu(fig, 'label', 'World');
h_uimenu_Transform = uimenu(fig, 'label', 'Diffeomorphism');
h_uimenu_Navigation = uimenu(fig, 'label', 'Navigation');
h_uimenu_Help = uimenu(fig, 'label', 'Help');

% data out
menus.h_uimenu_File = h_uimenu_File;
menus.h_uimenu_Edit = h_uimenu_Edit;
menus.h_uimenu_World = h_uimenu_World;
menus.h_uimenu_Transform = h_uimenu_Transform;
menus.h_uimenu_Navigation = h_uimenu_Navigation;
menus.h_uimenu_Help = h_uimenu_Help;

%% init each menu
function [h_uimenu_File_item_open, h_uimenu_File_item_save] =...
        file_menu(h_uimenu_File)

h_uimenu_File_item_open = uimenu(h_uimenu_File,...
    'label'     , 'Load Scenario',...
    'Callback'  , @file_open_call);

h_uimenu_File_item_save = uimenu(h_uimenu_File,...
    'label'     , 'Save Scenario',...
    'Callback'  , @file_save_call);

h_uimenu_File_item_restart = uimenu(h_uimenu_File,...
    'label'     , 'Restart nfsim GUI (CAUTION: clears workspace)',...
    'Callback'  , @file_restart_call);

function [] = edit_menu(h_uimenu_Edit)
        
function [h_uimenu_World_item, h_uimenu_World_place_obstacle] =...
        world_menu(h_uimenu_World)
h_uimenu_World_item(1) = uimenu(h_uimenu_World,...
    'label'     , 'Load',...
    'Callback'  , @world_load_call);

h_uimenu_World_item(2) = uimenu(h_uimenu_World,...
    'label'     , 'Save',...
    'Callback'  , @world_save_call);

h_uimenu_World_item(3) = uimenu(h_uimenu_World,...
    'label'     , 'Default',...
    'Callback'  , @world_default_call);

h_uimenu_World_item(4) = uimenu(h_uimenu_World,...
    'label'     , 'Space Dimension',...
    'Callback'  , @world_dimension_call);

h_uimenu_World_item(5) = uimenu(h_uimenu_World,...
    'label'     , 'Boundary',...
    'Callback'  , @world_boundary_call);

h_uimenu_World_place_obstacle = uimenu(h_uimenu_World,...
    'label'     , 'Place Obstacle',...
    'Callback'  , @draw_circle_call);

h_uimenu_World_item(7) = uimenu(h_uimenu_World,...
    'label'     , 'Configure Agents',...
    'Callback'  , @config_agent_call);
        
function [h_uimenu_Transform_item] = ...
    diffeomorphism_menu(h_uimenu_Transform)
h_uimenu_Transform_item(1) = uimenu(h_uimenu_Transform,...
    'label'     , 'Select diffeomorphism',...
    'Callback'  , @transform_select_diffeomorphism_call);
        
function [h_uimenu_Navigation_item] = ...
    navigation_menu(h_uimenu_Navigation)

h_uimenu_Navigation_item(1) = uimenu(h_uimenu_Navigation,...
    'label'     , 'Select Navigation Function/Potential Field',...
    'Callback'  , @nav_select_nf_call);

h_uimenu_Navigation_item(2) = uimenu(h_uimenu_Navigation,...
    'label'     , 'Navigate',...
    'Enable'    , 'off',...
    'Callback'  , @navigate_call);

h_uimenu_Navigation_item(3) = uimenu(h_uimenu_Navigation,...
    'label'     , 'Pause',...
    'Enable'    , 'off',...
    'Callback'  , @pause_call);

h_uimenu_Navigation_item(4) = uimenu(h_uimenu_Navigation,...
    'label'     , 'Stop',...
    'Enable'    , 'off',...
    'Callback'  , @stop_call);
        
function [h_uimenu_Help_item] = help_menu(h_uimenu_Help)
h_uimenu_Help_item(1) = uimenu(...
    'Parent'    , h_uimenu_Help,...
    'label'     , 'Product Help',...
    'Callback'  , @product_help);

h_uimenu_Help_item(2) = uimenu(...
    'Parent'    , h_uimenu_Help,...
    'label'     , 'About nfsim',...
    'Callback'  , @help_about_call);
